services:
  - type: web
    name: gocbt-license
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: APP_SECRET
        generateValue: true
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: PAYSTACK_PUBLIC_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: PRODUCT_CODE
        value: gocbt-desktop
      - key: MAX_DEVICES
        value: "1"
